name = "nutrition-risk-engine"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "nutrition-db"
database_id = "42b27e15-f705-421c-b06e-aab8b39311b5"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "91f9fd6cfce74bd0a2c5afe2c55b6b5f"
preview_id = "91f9fd6cfce74bd0a2c5afe2c55b6b5f"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true