name = "nutrition-risk-engine"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "nutrition-db"
database_id = "42b27e15-f705-421c-b06e-aab8b39311b5"
